#region Copyright Notice

// Copyright (c) by Achilles Software, All rights reserved.
//
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Send questions regarding this copyright notice to: mailto:Todd.Thomson@achilles-software.com

#endregion

#region Namespaces

using Achilles.Acme.Composition.Modules;

using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

using System;

#endregion

namespace Achilles.Acme.Plugins
{
    public abstract class PluginBase : IPlugin, IModule
    {
        #region Constructor

        public PluginBase()
        {
        }

        #endregion

        #region IModule Methods

        void IModule.Initialize( IServiceCollection services )
        {
            var serviceProvider = services.BuildServiceProvider();

            var configuration = serviceProvider.GetRequiredService<IConfiguration>();
            var env = serviceProvider.GetRequiredService<IHostingEnvironment>();

            ConfigureServices( services, configuration );
            Configure( env );
        }

        public virtual void ConfigureServices( IServiceCollection services, IConfiguration configuration )
        {
        }

        public virtual void Configure( IHostingEnvironment env )
        {
        }

        #endregion

        #region IPlugin Members

        /// <summary>
        /// Gets the autogenerated plugin key.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Gets the plugin unique id.
        /// </summary>
        public abstract Guid UId
        {
            get;
        }

        public abstract string Description
        {
            get;
        }

        public abstract string Name
        {
            get;
        }

        public abstract int Type
        {
            get;
        }

        public abstract String Version
        {
            get;
        }

        #endregion
    }
}
